### ISSUE TITLE
SSH Login Credentials - V3 Image

### ISSUE THREAD

**Issue by GaltresIT** [zafersn/WiFi-RC-Controller-With-Camera#12]
What is the Username and Password for the V3 image in the Readme file? 

I want to use the Pi for more than this project.

Tried the Raspbian default combination but had no luck. (pi/raspberry)

Thanks

**Comment by zafersn** [comment]
hi @GaltresIT . I'm sorry to write late. I understand. You want to use pi more than this project. Now, this feature is off. And I've been thinking about making this project completely open source code for a long time. With your problem, I can start to open-source the project.

You can follow the steps below in order to use the pi as desired.

1-
![Screen Shot](https://github.com/zafersn/WiFi-RC-Controller-With-Camera/blob/master/V3Images/images/Screenshot_20170122-205038.png)

In the Android app, you should enter 1.0711453, the entry where the pwm setting is made in the settings tab. This is a special code for raspberry. After you enter this code, say OK. You should see that the application running on Pi is shut down, then you should see the user login screen.
2-
username: pi password: zxcv. I will describe this issue in more detail at a more convenient time. I respond to this problem so that you can respond quickly


Beware: this image file is made up of little version of pi.

**Comment by zafersn** [comment]
Hi. @GaltresIT . Have you tried the instructions above?  tested and working in the most up-to-date state.

**Comment by teias27** [comment]
Merhaba, bu projede USB webcam kullanılabilir mi.

**Comment by zafersn** [comment]
Merhaba @teias27 usb webcam denemedim acıkcası. Ama bu konuyu birlikte inceleyebiliriz. Calıştığım için malesef şuanda uğraşacak vaktim yok ancak sizin vaktiniz varsa kodları açabilirim ve takıldığınız yerde bana soru sorabilirsiniz?. Kabul ederseniz bunun için yeni bir issues açıp soruyu ordan sormanız ve konuyu ordan devam ettirmemiz daha güzel olur.
