### ISSUE TITLE
relates to the tank

### ISSUE THREAD

**Issue by Born-to-kill** [zafersn/WiFi-RC-Controller-With-Camera#7]
Why do you have all the contrary? On the picture you connect to one pins and in the description it is indicated what you need to do differently? Why on one motor to connect 4 outputs instead of 3? This question relates to the tank
https://raw.githubusercontent.com/zafersn/WiFi-RC-Controller-With-Camera/master/V3Images/images/IMG_20151122_142027.jpg

**Comment by zafersn** [comment]
Hi @Born-to-kill  I'm sorry for the late reply.  

Because this case is related to my motor drive.  I shorted circuit the enable pins on the motor drive. So, instead of using 2 pins, I used one. Do not stick to this picture. It is not an example for you. The purpose of sharing this picture is to see the shape of the vehicle.
